Update build-srs.yml

diff --git a/.github/workflows/build-srs.yml b/.github/workflows/build-srs.yml
--- a/.github/workflows/build-srs.yml
+++ b/.github/workflows/build-srs.yml
@@ -46,11 +46,13 @@ jobs:
       - name: Compile json → srs
         run: |
           for file in rules-src/*.json; do
-            name=$(basename "$file" .json)
-            echo "Compiling $file → rules/$name.srs"
-            if ! ./sing-box rule-set compile "$file" -o "rules/$name.srs"; then
-              echo "Error compiling $file"
-              exit 1
+            if [ -f "$file" ]; then
+              name=$(basename "$file" .json)
+              echo "Compiling $file → rules/$name.srs"
+              if ! ./sing-box rule-set compile "$file" -o "rules/$name.srs"; then
+                echo "Error compiling $file"
+                exit 1
+              fi
             fi
           done
 
